### ISSUE TITLE
Process aborts in pypy with 0.1.17

### ISSUE THREAD

**Issue by chrysn** [mclab-hbrs/DTLSSocket#12]
It appears that #10 broke something when running on pypy.

I'm still in the process of figuring this out, but what I know so far:

* This affects 0.1.17, not 0.1.16, and has only been observed on pypy 7.3.16.
* I haven't managed to make DTLSSocket crash this way without aiocoap (but then again I don't manage to run its tests in any configuration).
* In the tox tests, this just manifests itself as "Fatal Python error: Aborted" followed by an abort / core dump.
* With a bit more manual installation, the error message is more prmising:

```
root@5bad5f0cc289:/aiocoap# python -m unittest
.s.................sRPython traceback:
  File "pypy_module_pypyjit.c", line 944, in portal_11
  File "pypy_interpreter_2.c", line 52260, in handle_bytecode__AccessDirect_None
  File "pypy_interpreter_3.c", line 33240, in dispatch_bytecode__AccessDirect_None
*** Invalid usage of a dying CPython object ***

cpyext, the emulation layer, detected that while it is calling
an object's tp_dealloc, the C code calls back a function that
tries to recreate the PyPy version of the object.  Usually it
means that tp_dealloc calls some general PyXxx() API.  It is
a dangerous and potentially buggy thing to do: even in CPython
the PyXxx() function could, in theory, cause a reference to the
object to be taken and stored somewhere, for an amount of time
exceeding tp_dealloc itself.  Afterwards, the object will be
freed, making that reference point to garbage.
>>> PyPy could contain some workaround to still work if
you are lucky, but it is not done so far; better fix the bug in
the CPython extension.
>>> This object is of type 'DTLSSocket.dtls.Connection'
Aborted
```

I'm not sure whether this only a PyPy issue or only a #10/Cython 3 issue -- it may well be that it is more a symptom of some shutdown related error (there is some unclean shutdown I couldn't trace back so far) that now manifests in an error.

Steps to reproduce:

```
$ docker run -it --rm docker.io/pypy:3 /bin/bash
$ git clone https://github.com/chrysn/aiocoap
$ git clone https://github.com/mclab-hbrs/DTLSSocket
$ pip install ./DTLSSocket
$ cd aiocoap
$ python -m unittest
```

**Comment by kabel42** [comment]
that sound like it might be caused by https://github.com/mclab-hbrs/DTLSSocket/blob/master/DTLSSocket/dtls.pyx#L159
could you try without the __del__ method? 
If that works, we might need to pass the underlying c pointer instead of a python object.

**Comment by chrysn** [comment]
Indeed, when removing that `__del__` completely, things do pass. (I had previously just removed the content of that function).

Trying more along those lines.

**Comment by kabel42** [comment]
oh, i thought the `session.getSession()` in both `close` and `resetPeer` would be a problem because cython3 seems to handle `__del__` similar to `__dealloc__`.
Maybe we can call the close somewhere else?

**Comment by chrysn** [comment]
It appears that around socket-ish objects it's generally good practice to have a `.close()` method, and only when the thing was not closed it would call that automatically at `__del__` time (but may also leak data because deletion is kinda not guaranteed anyway).

Just renaming the `__del__()` to `close()` does pass the tests, but I'd guess it's leaking resources. I'm modifying aiocoap to call those close methods…

**Comment by chrysn** [comment]
Hm, aiocoap already does call `myDTLS.close(session)` before even letting the session be dropped.

(That's not part of the issue: the empty \__del__ does cause the crash no matter whether or not I'm calling myDTLS.close on it or not).

So, one of the two things the current del does I do already anyway. I can just call resetPeer instead. As the code tells me, this stops retransmissions and frees the peer -- should have done that anyway. Actually, resetPeer calls close anyway if the state calls for it.

---

So, where do we go from here? Do we hope to save `__del__` by poking around in cython until it at least lets us pass with an empty `__del__` (as a starting point), or do we just document that connections should not be silently dropped and always have their `resetPeer` method called before going out of scope?

**Comment by kabel42** [comment]
can you try replacing `__del__` with
``` python
  def __dealloc__(self):
    tdtls.dtls_reset_peer(self.d.ctx, tdtls.dtls_get_peer(self.d.ctx, &self.session))
```

**Comment by chrysn** [comment]
That segfaults:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f74c194894b in dtls_destroy_peer (ctx=0x10ca1b0, peer=0x0, unlink=1) at DTLSSocket/tinydtls/dtls.c:1656
1656      if (peer->state != DTLS_STATE_CLOSED && peer->state != DTLS_STATE_CLOSING)
(gdb) print peer
$1 = (dtls_peer_t *) 0x0
```

**Comment by kabel42** [comment]
ok, we shouldn't try to delete peer if we already did before, maybe:
``` python
  def __dealloc__(self):
    peer = tdtls.dtls_get_peer(self.d.ctx, &self.session)
    if peer:
      tdtls.dtls_reset_peer(self.d.ctx, peer)
```

**Comment by chrysn** [comment]
... but that may just be because I'm calling resetPeer from Python. If I don't do that, thigns run throug.

**Comment by chrysn** [comment]
Yes, that's looking good. We should add the same check to resetPeer (otherwise calling that twice is a segfault), I'll prepare a patch.

**Comment by chrysn** [comment]
Pushed to #13.

I do have the suspicion that there is still something odd -- the mere presence of a \__del__ should not break in such a way. May be related to the both the Connection and the Session that is passed into its constructor having independent session_t objects, but then, I don't see through why those are separate in the first place, so maybe I'm missing something.

**Comment by kabel42** [comment]
maybe `__del__` is called from `__dealloc__` and then `session.getSession()` is a problem?

**Comment by chrysn** [comment]
The "Invalid usage" crash happens even with `def __del__(self): pass`.

**Comment by kabel42** [comment]
weird, sounds like a cython/pypy problem `__del__` should be valid for python>=3.4 and ignored for anything lower

**Comment by kabel42** [comment]
maybe a `def __del__(self): pass` in `cdef class Session` would have helped:
"Even more obscure: the same is true, for old-style classes, if you attach the `__del__` to an instance (even in CPython this does not work with new-style classes). You get a RuntimeWarning in PyPy. To fix these cases just make sure there is a `__del__` method in the class to start with (even containing only pass; replacing or overriding it later works fine)." -- https://doc.pypy.org/en/latest/cpython_differences.html

**Comment by chrysn** [comment]
It's not the combination of those two `__del__`: The crash happens when there exists a `__del__` on the Connection, the presence of a `__del__` on Session has no influence in either direction (a del there but none on the Connection works fine too, but can't do anything for lack of a DTLS object).
